milvus:
  user: "default"
  password: ""
  url: "localhost"
  port: "19530"
  collection_name: "credit_card_graph_feature3"
  top_k: 100
  threshold:
  index_type: "HNSW"
  metric_type: "L2"
  index_params: {"M": 16, "efConstruction": 32}
paths:
  data : data/raw/creditcard.csv
  output_dir : data/final
  save_graphs : true